const adjective = [
    "Excited",
    "Anxious",
    "Overweight",
    "Demonic",
    "Jumpy",
    "Misunderstood",
    "Squashed",
    "Gargantuan",
    "Broad",
    "Crooked",
    "Curved",
    "Deep",
    "Even",
    "Excited",
    "Anxious",
    "Overweight",
    "Demonic",
    "Jumpy",
    "Misunderstood",
    "Squashed",
    "Gargantuan",
    "Broad",
    "Crooked",
    "Curved",
    "Deep",
    "Even",
    "Flat",
    "Hilly",
    "Jagged",
    "Round",
    "Shallow",
    "Square",
    "Steep",
    "Straight",
    "Thick",
    "Thin",
    "Cooing",
    "Deafening",
    "Faint",
    "Harsh",
    "High-pitched",
    "Hissing",
    "Hushed",
    "Husky",
    "Loud",
    "Melodic",
    "Moaning",
    "Mute",
    "Noisy",
    "Purring",
    "Quiet",
    "Raspy",
    "Screeching",
    "Shrill",
    "Silent",
    "Soft",
    "Squeaky",
    "Squealing",
    "Thundering",
    "Voiceless",
    "Whispering",
];
const object = [
    "Taco",
    "Operating System",
    "Sphere",
    "Watermelon",
    "Cheeseburger",
    "Apple Pie",
    "Spider",
    "Dragon",
    "Remote Control",
    "Soda",
    "Barbie Doll",
    "Watch",
    "Purple Pen",
    "Dollar Bill",
    "Stuffed Animal",
    "Hair Clip",
    "Sunglasses",
    "T-shirt",
    "Purse",
    "Towel",
    "Hat",
    "Camera",
    "Hand Sanitizer",
    "Photo",
    "Dog Bone",
    "Hair Brush",
    "Birthday Card",
];

export default function getRandomName() {
    return (
        adjective[Math.floor(Math.random() * adjective.length)] +
        " " +
        object[Math.floor(Math.random() * object.length)]
    );
}
